import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  weight: ["400", "600", "800"],
  subsets: ["latin-ext"],
  display: "swap",
  preload: true
});

export const metadata: Metadata = {
  title: "Rajske Kočije - Pogrebne usluge Beograd | Dostupni 24 časa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`min-h-full flex flex-col ${manrope.className}`}>{children}</body>
    </html>
  );
}
